AnimeBoard 1.13.0-BETA (#2)
* Fix Command Error

* Add BetterReload support

* Refactor project

* Packet Functionality for 1.20.3+

- Adds packet-based scoreboards for 1.20.3+
- Fixes broken built in placeholders in the title
- Fixes a NoClassDefFoundError I introduced in a prior commit

* Comments, version changes, and microoptimization

* Update ReadMe

* Optimize sending packets

* Fix potential error?

This being absent should have created an error, but I haven't seen any so far...