Packet Functionality for 1.20.3+
- Adds packet-based scoreboards for 1.20.3+
- Fixes broken built in placeholders in the title
- Fixes a NoClassDefFoundError I introduced in a prior commit